= Objeto y alcance
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

== Objeto

Este documento constituye el Código de Prácticas Tecnológicas que implementa de forma práctica la estrategia de transformación digital ágil del Ayuntamiento de Barcelona (la “Estrategia”), en conformidad con los Estándares de Servicios Digitales de la Ciudad enunciados en Setiembre del 2017.

Este Código consiste principalmente en una relación de principios y requerimientos directos y claros, que *permiten entender de forma rápida* los distintos elementos de la transformación digital en marcha en la Ciudad de Barcelona.
Tiene como objetivo permitir a los responsables de la gobernanza y de la gestión de proyectos de servicios digitales asegurar que éstos se alinean con la Estrategia del Ayuntamiento de Barcelona en éste ámbito.

El Código está planteado como un documento práctico de referencia y no contiene justificaciones teóricas para las políticas propuestas ni referencias a ejemplos, salvo en contadas ocasiones.

Las directrices concretas están basadas en prácticas ejemplares de varios países y contextos.
El Reino Unido, EEUU, Suecia y Holanda ente muchos otros, han implementado políticas innovadoras a nivel estatal de tecnologías abiertas y desarrollos _agile_.

== Alcance y aplicación

Este Código de Prácticas Tecnológicas es de aplicación en la gestión y gobernanza de los proyectos de tecnología e innovación que se incluyan dentro del Plan de Transformación Digital Ágil, tanto por el Instituto Municipal de Informática (IMI) como por otras entidades y departamentos dependientes del Ayuntamiento de Barcelona.
Asimismo concierne el diseño y construcción de todos los servicios digitales del Ayuntamiento, entendiendo como tales los servicios de gestión y entrega de la información mediante plataformas y dispositivos digitales.

Se dirige a todos los líderes y responsables de las unidades del Grupo Municipal, los administradores de programas y el personal implicado en la implementación de esta Estrategia.
Los responsables de cada Gerencia tienen el cometido último de asegurar que las directrices de la Estrategia y de este Código se implementen.

La puesta en marcha de estos principios y directrices se hará a través de la realización de los proyectos de transformación digital ágil del Ayuntamiento, gestionados principalmente por el IMI.
Estos proyectos permitirán la dedicación de recursos, la creación de infraestructura y la adquisición de competencias para realizar estas transformaciones.
De esta manera, la gestión del cambio que supone la aplicación de estas prácticas dentro del Ayuntamiento se realizará de manera iterativa a través de proyectos concretos.
Algunos proyectos y sus ampliaciones (por ejemplo, Decidimos Barcelona, Sentilo, BIMA) ya cumplen en buena medida las directrices indicadas aquí, otros lo irán consiguiendo con un proceso de aplicación más progresivo.

== Estructura

Este documento se estructura en un conjunto de principios generales, apoyados por directrices que corresponden a los tres principales ejes de la Estrategia de transformación digital ágil del Ayuntamiento de Barcelona:

* El desarrollo de servicios digitales ágiles

* La soberanía tecnológica, apoyada en el uso de estándares abiertos y de software libre

* La gestión ética y segura de datos y de datos abiertos

Este documento es complementario y no sustituye a ninguna política de la organización ni regulación municipal o de otros ámbitos

Este código de prácticas tecnológicas se acompaña de dos documentos de apoyo para favorecer el desarrollo del Plan de Transformación Digital Ágil: la Guía sobre Metodologías Ágiles y la Guía sobre Soberanía Tecnológica.
Sin embargo, el Plan se implementa a través de las Guías de Contratación del Ayuntamiento, en especial la Guía de Compra Pública de TIC y la Guía de Compra Innovadora.
En relación a la gestión responsable y ética de datos, elemento esencial del Plan de Transformación Digital Ágil (en especial la estrategia de Datos Abiertos y para el bien común, los proyectos _Data Driven_ y la interoperabilidad basada en formatos de datos abiertos), las correspondientes directivas y su puesta en práctica se desarrollarán en una nueva Medida de Gobierno sobre la _Estrategia de Gestión Responsable y Ética de Datos en el Ayuntamiento de Barcelona_, que se concretará con los necesarios detalles técnicos, procesos y responsabilidades.
